#########################
# configuration section #
#########################

ZTEXPREFIX=../../..

JARTARGET=Debug.jar
CLASSTARGETS=Debug.class
CLASSEXTRADEPS=
#CLASSEXTRADEPS:=$(shell echo $(ZTEXPREFIX)/java/ztex/*.java)

IHXTARGETS=debug.ihx
IHXEXTRADEPS=
#IHXEXTRADEPS:=$(shell echo $(ZTEXPREFIX)/include/*.h)
EXTRAJARFILES=debug.ihx

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk
