#########################
# configuration section #
#########################

ZTEXPREFIX=../../..

JARTARGET=FlashDemo.jar
CLASSTARGETS=FlashDemo.class
CLASSEXTRADEPS=
#CLASSEXTRADEPS:=$(shell echo $(ZTEXPREFIX)/java/ztex/*.java)

IHXTARGETS=flashdemo.ihx
IHXEXTRADEPS=
#IHXEXTRADEPS:=$(shell echo $(ZTEXPREFIX)/include/*.h)
EXTRAJARFILES=flashdemo.ihx

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk
